FROM alpine AS builder

RUN apk add --no-cache nasm

COPY minimal.S /readflag.S
RUN nasm -f bin -o /readflag /readflag.S && \
    chmod a+x,u+s /readflag


FROM scratch

ADD --chown=root:root --chmod=400 flag /flag
COPY --from=builder /readflag /readflag

CMD ["/readflag"]
