name: <ACTION_NAME>

on:
  push:
    branches: ["main"]
    paths:
      <DEPENDENCY_PATHS>
      - ".github/workflows/base.<ACTION_FILE>.yml"
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  NAME: <NAME>
  TAG: <TAG>

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}/${{ env.NAME }}
          tags: |
            ${{ env.TAG }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: base/${{ env.NAME }}
          file: base/${{ env.NAME }}/<DOCKERFILE>
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true
          
      - name: Get lower case repository name
        id: lower_repo
        run: |
          export REPO_NAME=${{ github.event.repository.name }}
          echo "repo_name=${REPO_NAME@L}" >> $GITHUB_OUTPUT

      - name: Prune old packages
        uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          package: ${{ steps.lower_repo.outputs.repo_name }}/${{ env.NAME }}
          use-regex: true
          exclude-tags: <PRUNE_TAG_REGEX>
          validate: true
          dry-run: true
          delete-untagged: true
          delete-ghost-images: true
          delete-partial-images: true
