name: Base-PHP 8

on:
  push:
    branches: ["main"]
    paths:
      - "base/php/**"
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  NAME: php
  ORGANIZATION: s1um4i
  REPOSITORY: challenge-base
  TAG: alpine

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}/${{ env.NAME }}
          tags: |
            ${{ env.TAG }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: base/${{ env.NAME }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true

      - name: Prune old packages
        uses: vlaurin/action-ghcr-prune@v0.6.0
        with:
          dry-run: false
          token: ${{ secrets.GITHUB_TOKEN }}
          organization: ${{ env.ORGANIZATION }}
          container: ${{ env.REPOSITORY }}/${{ env.NAME }}
          keep-tags: |
            alpine$
          prune-untagged: true
