name: Base-Xinetd

on:
  push:
    branches: ["main"]
    paths:
      - "base/xinetd/**"
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  NAME: xinetd
  ORGANIZATION: s1um4i
  REPOSITORY: challenge-base

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}/${{ env.NAME }}
          tags: |
            alpine

      - name: Docker setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Docker setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: base/${{ env.NAME }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          push: true

      - name: Prune old packages
        uses: vlaurin/action-ghcr-prune@v0.6.0
        with:
          dry-run: false
          token: ${{ secrets.GITHUB_TOKEN }}
          organization: ${{ env.ORGANIZATION }}
          container: ${{ env.REPOSITORY }}/${{ env.NAME }}
          keep-tags: |
            "alpine"
          keep-last: 5
          prune-untagged: true
